version: '2'
services:
    nginx-proxy:
        build: ./build
        restart: always
        environment: 
          - DHPARAM_GENERATION=false
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - /etc/nginx/vhost.d
          - /usr/share/nginx/html
        networks:
          - nginx-proxy-network

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        environment: 
          - "DEFAULT_EMAIL=${DEFAULT_EMAIL}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        volumes_from: 
          - container:nginx-proxy_nginx-proxy_1
        networks:
          - nginx-proxy-network

    whoami:
        image: jwilder/whoami
        restart: always
        container_name: whoami
        environment:
          - VIRTUAL_HOST=whoami.local
        networks:
          - nginx-proxy-network
networks:
  nginx-proxy-network:
    external:
      name: reverseproxy_default
