version: '2'
services:
    nginx-proxy:
        build: ./build
        restart: always
        container_name: nginx-proxy
        ports:
        - "80:80"
        volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
          - nginx-proxy-network

    whoami:
        image: jwilder/whoami
        restart: always
        container_name: whoami
        environment:
        - VIRTUAL_HOST=whoami.local
        networks:
          - nginx-proxy-network
networks:
  nginx-proxy-network:
    external:
      name: reverseproxy_default
