version: "2.0"

services:
  nginx:
    image: nginx:1.11
    volumes:
      - "${APP_DIR}:/var/www/html:ro"
      - "${NGINX_CONF_DIR}:/etc/nginx/conf.d"
    depends_on:
      - php
      - phpmyadmin
    networks:
      - server
      - nginx-proxy-network
      - database
    environment:
      - VIRTUAL_HOST=${DOMAINS},${PMA_DOMAINS}

  php:
    image: zurbaev/php71-common
    expose:
      - "9000"
    volumes:
      - "${APP_DIR}:/var/www/html"
    depends_on:
      - mysql
    networks:
      - database
      - server

  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - "80"
    environment:
      PMA_HOST: ${PMA_DOMAINS}
    depends_on:
      - mysql
    networks:
      - database
      - server

networks:
  database:
  server:
  nginx-proxy-network:
    external:
        name: reverseproxy_default
