version: "2.0"

services:
  nginx:
    image: nginx:1.17
    volumes:
      - "${APP_DIR}:/var/www/html:ro"
      - "${NGINX_CONF_DIR}:/etc/nginx/conf.d"
    networks:
      - nginx-proxy-network
    environment:
      - VIRTUAL_HOST=${DOMAINS}

networks:
  nginx-proxy-network:
    external:
        name: reverseproxy_default
