services:
  nginx-proxy:
    restart: ${RESTART:-"unless-stopped"}
    container_name: "${COMPOSE_PROJECT_NAME}_nginx-proxy"
    build: ./build
    environment:
      - DHPARAM_GENERATION=${DHPARAM_GENERATION:-false}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_SOCK_FILE:-/var/run/docker.sock}:/tmp/docker.sock
      - reverseproxy_vhost:/etc/nginx/vhost.d
      - reverseproxy_html:/usr/share/nginx/html
      - ${NGINX_CONF_FILE:-./nginx.d/nginx.conf}:/etc/nginx/nginx.conf
      - certs:/etc/nginx/certs:rw
    networks:
      - reverseproxy_default

  whoami:
    restart: ${RESTART:-"unless-stopped"}
    image: acrossoffwest/whoami:master
    environment:
      - VIRTUAL_HOST=whoami.local
    networks:
      - reverseproxy_default

  letsencrypt:
    restart: ${RESTART:-"unless-stopped"}
    profiles:
      - production
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes:
      - certs:/etc/nginx/certs:rw
      - ${DOCKER_SOCK_FILE:-/var/run/docker.sock}:/var/run/docker.sock
    volumes_from:
      - nginx-proxy
    networks:
      - reverseproxy_default

networks:
  reverseproxy_default:
    external: true

volumes:
  reverseproxy_vhost:
  reverseproxy_html:
  certs:
